// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Celebrity struct {
	ID           int    `json:"id"`
	Fullname     string `json:"Fullname"`
	Nationality  string `json:"Nationality"`
	ReqPhotoPath string `json:"ReqPhotoPath"`
}

type Mutation struct {
}

type NewCelebrity struct {
	Fullname     string `json:"Fullname"`
	Nationality  string `json:"Nationality"`
	ReqPhotoPath string `json:"ReqPhotoPath"`
}

type Query struct {
}
