package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"lab10/graph/model"
)

// CreateCelebrity is the resolver for the createCelebrity field.
func (r *mutationResolver) CreateCelebrity(ctx context.Context, input model.NewCelebrity) (*model.Celebrity, error) {
	c := model.Celebrity{
		Fullname:     input.Fullname,
		Nationality:  input.Nationality,
		ReqPhotoPath: input.ReqPhotoPath,
	}

	if err := r.DB.Create(&c).Error; err != nil {
		return nil, err
	}

	return &c, nil
}

// PutCelebrity is the resolver for the putCelebrity field.
func (r *mutationResolver) PutCelebrity(ctx context.Context, id int, input model.NewCelebrity) (*model.Celebrity, error) {
	var existing model.Celebrity
	if err := r.DB.First(&existing, id).Error; err != nil {
		return nil, err
	}

	existing.Fullname = input.Fullname
	existing.Nationality = input.Nationality
	existing.ReqPhotoPath = input.ReqPhotoPath

	if err := r.DB.Save(&existing).Error; err != nil {
		return nil, err
	}

	return &existing, nil
}

// DeleteCelebrity is the resolver for the deleteCelebrity field.
func (r *mutationResolver) DeleteCelebrity(ctx context.Context, id int) (*model.Celebrity, error) {
	var existing model.Celebrity

	if err := r.DB.First(&existing, id).Error; err != nil {
		return nil, err
	}

	if err := r.DB.Delete(&existing).Error; err != nil {
		return nil, err
	}

	return &existing, nil
}

// Celebrities is the resolver for the celebrities field.
func (r *queryResolver) Celebrities(ctx context.Context) ([]*model.Celebrity, error) {
	var cels []*model.Celebrity
	if err := r.DB.Find(&cels).Error; err != nil {
		return nil, err
	}

	return cels, nil
}

// Celebrity is the resolver for the celebrity field.
func (r *queryResolver) Celebrity(ctx context.Context, id *int) (*model.Celebrity, error) {
	var existing model.Celebrity
	if err := r.DB.Find(&existing, id).Error; err != nil {
		return nil, err
	}

	return &existing, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
